### PR TITLE
Made challenge 8/9 consistent with challenge 7/9

### PR DESCRIPTION
**Pull request by radujipa**
* challenge 8 now asks you to use the theme you created previously in challenge 7

screen shot 2015-10-23 at 14 26 22

@alex5imon @convolu could you please review this?

### CODE REVIEW

**Comment by radujipa** [comment]
related to https://github.com/KanoComputing/peldins/issues/2096

**Comment by alex5imon** [comment]
Very elegant solution Mr Jipa :+1: :+1: :+1:

**Comment by convolu** [comment]
Looks good :shipit:

**Comment by radujipa** [comment]
Why thank you indeed Mr Simon and Voloudakis, I shall merge this with haste :shipit:

**Pull request merged**
